
const Fooddata = [
    {
        id: 1,
        rname: "TOMATO SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341217/ij9anrnexmcawxvhvg6c.jpg",
        address: "North Indian, Biryani, Mughlai",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341217/ij9anrnexmcawxvhvg6c.jpg",
        somedata: " 1175 + order placed from here recently",
        price: "₹165",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341217/ij9anrnexmcawxvhvg6c.jpg",
        category:"Soups"
    },
    {
        id: 2,
        rname: "SWEET CORN VEG. SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341218/zig2fqndtgqjtbuaslpy.jpg",
        address: "Street Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341218/zig2fqndtgqjtbuaslpy.jpg",
        somedata: " 2525 + order placed from here recently",
        price: "₹165",
        rating: "3.9",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341218/zig2fqndtgqjtbuaslpy.jpg",
        category:"Soups"
    },
    {
        id: 3,
        rname: "HOT & SOUR VEG. SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341218/leaqf44pyhhqdheizlvq.jpg",
        address: "Pizza, Fast Food, Pasta",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341218/leaqf44pyhhqdheizlvq.jpg",
        somedata: " 650 + order placed from here recently",
        price: "₹165",
        rating: "4.2",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341218/leaqf44pyhhqdheizlvq.jpg",
        category:"Soups"
    },
    {
        id: 4,
        rname: "VEG. SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341220/gpfxklxc7wcczu7h1dd7.jpg",
        address: "Momos",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341220/gpfxklxc7wcczu7h1dd7.jpg",
        somedata: " 300 + order placed from here recently",
        price: "₹165",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341220/gpfxklxc7wcczu7h1dd7.jpg",
        category:"Soups"
    },
    {
        id: 5,
        rname: "MANCHOW SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341215/fjkfhamxceqllrmz7uff.jpg",
        address: "North Indian",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341215/fjkfhamxceqllrmz7uff.jpg",
        somedata: "1050 + order placed from here recently",
        price: "₹165",
        rating: "4.0",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341215/fjkfhamxceqllrmz7uff.jpg",
        category:"Soups"
    },
    {
        id: 6,
        rname: "LEMON CORIANDER",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341217/kpisaanh9rf85odqdlly.jpg",
        address: "Wraps FastFood, Chines",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341217/kpisaanh9rf85odqdlly.jpg",
        somedata: " 1100 + order placed from here recently",
        price: "₹165",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341217/kpisaanh9rf85odqdlly.jpg",
        category:"Soups"
    },
    {
        id: 7,
        rname: "Chicken Clear soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341233/g1drhuejv8ihpevcydqp.jpg",
        address: "North Indian, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341233/g1drhuejv8ihpevcydqp.jpg",
        somedata: "500 + order placed from here recently",
        price: "₹195",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341233/g1drhuejv8ihpevcydqp.jpg",
        category:"Soups"
    },
    {
        id: 8,
        rname: "Chicken Sweet corn Soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341189/qongkwuiy36d65jukdyp.jpg",
        address: "Tea, Coffee, Shake, Beverages",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341189/qongkwuiy36d65jukdyp.jpg",
        somedata: "500 + order placed from here recently",
        price: "₹195",
        rating: "3.2",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341189/qongkwuiy36d65jukdyp.jpg",
        category:"Soups"
    },
    {
        id: 9,
        rname: "Chicken Hot and Sour soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/akgafvbwyz1ahddwoqs9.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/akgafvbwyz1ahddwoqs9.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹195",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/akgafvbwyz1ahddwoqs9.jpg",
        category:"Soups"
    },
    {
        id: 10,
        rname: "Chicken Manchow Soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341195/x4tpfjf7pvladsxtp9a1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341195/x4tpfjf7pvladsxtp9a1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹195",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341195/x4tpfjf7pvladsxtp9a1.jpg",
        category:"Soups"
    },
    {
        id: 11,
        rname: "French Fries",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹150",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chicken Starters(Veg)"
    },
    {
        id: 12,
        rname: "Veg Spring Rolls",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 13,
        rname: "Honey Chilli Potato",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 14,
        rname: "Chilli Potato",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹225",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 15,
        rname: "Veg Manchurian Dry",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 16,
        rname: "Chilli Crispy Corn",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 17,
        rname: "Crispy Veg Salt and Pepper",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 18,
        rname: "Chilli Paneer Dry",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 19,
        rname: "Chilli Mushroom",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 20,
        rname: "Chicken Spring roll",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 21,
        rname: "Chilli Chicken(10pcs)",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 22,
        rname: "Chicken pepper salt",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 23,
        rname: "Chicken Manchurian",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 24,
        rname: "Crispy Chicken Wings",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 25,
        rname: "Chicken Lollipop",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 26,
        rname: "Veg Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 26,
        rname: "Veg Chilli Garlic Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹225",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 27,
        rname: "Veg Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 28,
        rname: "Veg Singapuri Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 29,
        rname: "Egg Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 30,
        rname: "Egg Chilli Garlic Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 31,
        rname: "Chicken Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹250",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 32,
        rname: "Chicken Chilli Garlic Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 33,
        rname: "Chicken Singapuri Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 34,
        rname: "Veg Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 35,
        rname: "Veg Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹225",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 36,
        rname: "Veg Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹235",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 37,
        rname: "Egg Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 38,
        rname: "Egg Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹250",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 39,
        rname: "Egg Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 40,
        rname: "Chicken Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹250",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 41,
        rname: "Chicken Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 42,
        rname: "Chicken Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 43,
        rname: "Prawn Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹330",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 44,
        rname: "Prawn Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 45,
        rname: "Prawn Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 46,
        rname: "Veg Steamed Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹170",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Momos"
    },
    {
        id: 47,
        rname: "Veg Fried Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹180",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Momos"
    },
    {
        id: 48,
        rname: "Veg Kurkure Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹200",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Momos"
    },
    {
        id: 49,
        rname: "Paneer Steamed Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/pkumtvbgcpxzmoc8459a.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/pkumtvbgcpxzmoc8459a.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹175",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/pkumtvbgcpxzmoc8459a.jpg",
        category:"Momos"
    },
    {
        id: 50,
        rname: "Paneer Fried Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/ttmxtyvpqyn1az3yns5b.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/ttmxtyvpqyn1az3yns5b.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹200",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/ttmxtyvpqyn1az3yns5b.jpg",
        category:"Momos"
    },
    {
        id: 51,
        rname: "Paneer Kurkure Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        category:"Momos"
    },
    {
        id: 52,
        rname: "Chicken Steamed Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/sgbuukmb2qhg1jckshtk.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/sgbuukmb2qhg1jckshtk.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹220",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/sgbuukmb2qhg1jckshtk.jpg",
        category:"Momos"
    },
    {
        id: 53,
        rname: "Chicken Fried Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/ghlk2cfzq4kvciba4wt1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/ghlk2cfzq4kvciba4wt1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹220",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/ghlk2cfzq4kvciba4wt1.jpg",
        category:"Momos"
    },
    {
        id: 54,
        rname: "Chicken Kurkure Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/rxzxyzowh0gjsbavodb8.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/rxzxyzowh0gjsbavodb8.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/rxzxyzowh0gjsbavodb8.jpg",
        category:"Momos"
    },
    {
        id: 55,
        rname: "Veg Chopsy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/p4lix5iwqfjbed7dng46.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/p4lix5iwqfjbed7dng46.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹210",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/p4lix5iwqfjbed7dng46.jpg",
        category:"Chopsy"
    },
    {
        id: 56,
        rname: "Egg Chopsy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/hfysslckzazth2rvygqz.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/hfysslckzazth2rvygqz.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹220",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/hfysslckzazth2rvygqz.jpg",
        category:"Chopsy"
    },
    {
        id: 57,
        rname: "Chicken Chopsy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/xppqt4fursxtvzog893i.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/xppqt4fursxtvzog893i.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹245",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/xppqt4fursxtvzog893i.jpg",
        category:"Chopsy"
    },
    {
        id: 58,
        rname: "American Chopsy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/kxnchteoipg7afzauqws.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/kxnchteoipg7afzauqws.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹265",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/kxnchteoipg7afzauqws.jpg",
        category:"Chopsy"
    },
    {
        id: 59,
        rname: "Veg Manchurian",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375666/gcsuztzojcdyxh1hhe23.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375666/gcsuztzojcdyxh1hhe23.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹325",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375666/gcsuztzojcdyxh1hhe23.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 60,
        rname: "Veg Sweet and Sour",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 61,
        rname: "Mixed Veg Hot Garlic",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 62,
        rname: "Mushroom Chilli Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 63,
        rname: "Veg Baby Corn Garlic Sauce",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 64,
        rname: "Paneer Hot Garlic Sauce",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/habjfpwxokayyvnpfhh3.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/habjfpwxokayyvnpfhh3.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/habjfpwxokayyvnpfhh3.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 65,
        rname: "Chicken Manchurian Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/otnbbups4fxwd8bfw1b8.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/otnbbups4fxwd8bfw1b8.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/otnbbups4fxwd8bfw1b8.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 66,
        rname: "Chicken Chilly Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 67,
        rname: "Chicken Hot Garlic",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/r6vazsbr1g50wdldragz.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/r6vazsbr1g50wdldragz.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/r6vazsbr1g50wdldragz.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 68,
        rname: "Honey Chilli Chicken Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/kgppbdlahlghi73m8eyv.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/kgppbdlahlghi73m8eyv.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/kgppbdlahlghi73m8eyv.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 69,
        rname: "Chicken Sweet & sour",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 70,
        rname: "Fried Rice /Noodles+Veg Manchurian",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 71,
        rname: "Chilli Potato+Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 72,
        rname: "Chilly Paneer+Noodle/Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹260",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 73,
        rname: "Fried Rice /Noodles+Chilli Chicken",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },

    {
        id: 74,
        rname: "Fried Rice /Noodles+Chicken Manchurian",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 75,
        rname: "Half Chilly Paneer+Half veg Hakka Noodle+2 Spring roll+2 Veg momo",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Veg Thali Combo"
    },
    {
        id: 75,
        rname: "Half Chilly Chicken+Half Chicken Hakka Noodle+2 Chicken Spring roll+2 Chicken momo",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹440",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"NonVeg Thali Combo"
    },



];

export default Fooddata;