
const Fooddata = [
    {
        id: 1,
        rname: "TOMATO SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/zfurqkasbkgnot2pyinf.jpg",
        address: "North Indian, Biryani, Mughlai",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/zfurqkasbkgnot2pyinf.jpg",
        somedata: " 1175 + order placed from here recently",
        price: "₹165",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/zfurqkasbkgnot2pyinf.jpg",
        category:"Soups"
    },
    {
        id: 2,
        rname: "SWEET CORN VEG. SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/u6e20s3mzybghzi6rwwo.jpg",
        address: "Street Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/u6e20s3mzybghzi6rwwo.jpg",
        somedata: " 2525 + order placed from here recently",
        price: "₹165",
        rating: "3.9",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/u6e20s3mzybghzi6rwwo.jpg",
        category:"Soups"
    },
    {
        id: 3,
        rname: "HOT & SOUR VEG. SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/mrxvghdlaqsnrtdyoeph.jpg",
        address: "Pizza, Fast Food, Pasta",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/mrxvghdlaqsnrtdyoeph.jpg",
        somedata: " 650 + order placed from here recently",
        price: "₹165",
        rating: "4.2",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/mrxvghdlaqsnrtdyoeph.jpg",
        category:"Soups"
    },
    {
        id: 4,
        rname: "VEG. SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480192/uexppq5swa4dvf06ebpi.jpg",
        address: "Momos",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480192/uexppq5swa4dvf06ebpi.jpg",
        somedata: " 300 + order placed from here recently",
        price: "₹165",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480192/uexppq5swa4dvf06ebpi.jpg",
        category:"Soups"
    },
    {
        id: 5,
        rname: "MANCHOW SOUP",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/gnzkxdv1qhbrjle2tqdw.jpg",
        address: "North Indian",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/gnzkxdv1qhbrjle2tqdw.jpg",
        somedata: "1050 + order placed from here recently",
        price: "₹165",
        rating: "4.0",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/gnzkxdv1qhbrjle2tqdw.jpg",
        category:"Soups"
    },
    {
        id: 6,
        rname: "LEMON CORIANDER",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/j2pr5rdms9ofsk9jelip.jpg",
        address: "Wraps FastFood, Chines",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/j2pr5rdms9ofsk9jelip.jpg",
        somedata: " 1100 + order placed from here recently",
        price: "₹165",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480188/j2pr5rdms9ofsk9jelip.jpg",
        category:"Soups"
    },
    {
        id: 7,
        rname: "Chicken Clear soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/rtymgbvmzqghryyfumjq.jpg",
        address: "North Indian, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/rtymgbvmzqghryyfumjq.jpg",
        somedata: "500 + order placed from here recently",
        price: "₹195",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/rtymgbvmzqghryyfumjq.jpg",
        category:"Soups"
    },
    {
        id: 8,
        rname: "Chicken Sweet corn Soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/niawrni1na3xyn9p16hi.jpg",
        address: "Tea, Coffee, Shake, Beverages",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/niawrni1na3xyn9p16hi.jpg",
        somedata: "500 + order placed from here recently",
        price: "₹195",
        rating: "3.2",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/niawrni1na3xyn9p16hi.jpg",
        category:"Soups"
    },
    {
        id: 9,
        rname: "Chicken Hot and Sour soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/pqupjjcmxklwp1lipr2f.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/pqupjjcmxklwp1lipr2f.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹195",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/pqupjjcmxklwp1lipr2f.jpg",
        category:"Soups"
    },
    {
        id: 10,
        rname: "Chicken Manchow Soup",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480181/hbaru0ewxjlxbhndlht7.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480181/hbaru0ewxjlxbhndlht7.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹195",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480181/hbaru0ewxjlxbhndlht7.jpg",
        category:"Soups"
    },
    {
        id: 11,
        rname: "French Fries",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/rdtheoii65d28u6zlg9r.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/rdtheoii65d28u6zlg9r.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹150",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/rdtheoii65d28u6zlg9r.jpg",
        category:"Chicken Starters(Veg)"
    },
    {
        id: 12,
        rname: "Veg Spring Rolls",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480192/dznqjeuxlisd4ev7tvz1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480192/dznqjeuxlisd4ev7tvz1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480192/dznqjeuxlisd4ev7tvz1.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 13,
        rname: "Honey Chilli Potato",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/efqkwlfm9xafr3yqeroo.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/efqkwlfm9xafr3yqeroo.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/efqkwlfm9xafr3yqeroo.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 14,
        rname: "Chilli Potato",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/ebefoyo1gt2bi0dnujl2.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/ebefoyo1gt2bi0dnujl2.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹225",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/ebefoyo1gt2bi0dnujl2.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 15,
        rname: "Veg Manchurian Dry",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/akjan5irws77hw5yeb9o.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/akjan5irws77hw5yeb9o.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/akjan5irws77hw5yeb9o.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 16,
        rname: "Chilli Crispy Corn",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/pmonpyzwytdrrim7ccjt.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/pmonpyzwytdrrim7ccjt.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/pmonpyzwytdrrim7ccjt.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 17,
        rname: "Crispy Veg Salt and Pepper",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/yxuzk17eyebhhxwybdbo.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/yxuzk17eyebhhxwybdbo.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/yxuzk17eyebhhxwybdbo.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 18,
        rname: "Chilli Paneer Dry",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/wwplh0qimxzxqkkphl2l.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/wwplh0qimxzxqkkphl2l.jpg",
        somedata: "2525 + order plaps://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpgced from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/wwplh0qimxzxqkkphl2l.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 19,
        rname: "Chilli Mushroom",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/gqmvrvhkcb3q4qo9nnwi.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/gqmvrvhkcb3q4qo9nnwi.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/gqmvrvhkcb3q4qo9nnwi.jpg",
        category:"Chinese Starters(Veg)"
    },
    {
        id: 20,
        rname: "Chicken Spring roll",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/yeu4s9jz5bpyilq8o8hr.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/yeu4s9jz5bpyilq8o8hr.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/yeu4s9jz5bpyilq8o8hr.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 21,
        rname: "Chilli Chicken(10pcs)",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 22,
        rname: "Chicken pepper salt",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/nqzg3kyfpvwpcxuieaah.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/nqzg3kyfpvwpcxuieaah.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/nqzg3kyfpvwpcxuieaah.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 23,
        rname: "Chicken Manchurian",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/xosalecd5zvsvmbo2slg.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/xosalecd5zvsvmbo2slg.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/xosalecd5zvsvmbo2slg.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 24,
        rname: "Crispy Chicken Wings",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/pvedngmoxvpxbws76xg1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/pvedngmoxvpxbws76xg1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/pvedngmoxvpxbws76xg1.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 25,
        rname: "Chicken Lollipop",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/ffv90isnevcesob2eh6m.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/ffv90isnevcesob2eh6m.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/ffv90isnevcesob2eh6m.jpg",
        category:"Chinese Starters(NonVeg)"
    },
    {
        id: 26,
        rname: "Veg Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/l1g9sw9trtvnrf6gldmz.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/l1g9sw9trtvnrf6gldmz.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/l1g9sw9trtvnrf6gldmz.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 26,
        rname: "Veg Chilli Garlic Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/cui3znnzho8todmkuptj.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/cui3znnzho8todmkuptj.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹225",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/cui3znnzho8todmkuptj.jpg",
        category:"Noodles and Rice Veg"
    },
    // {
    //     id: 27,
    //     rname: "Veg Noodles",
    //     imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
    //     address: "Burger, Sandwich, Fast Food",
    //     delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
    //     somedata: "2525 + order placed from here recently",
    //     price: "₹215",
    //     rating: "3.8",
    //     arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
    //     category:"Noodles and Rice Veg"
    // },
    {
        id: 28,
        rname: "Veg Singapuri Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/hgwosudozv2boql5xnww.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/hgwosudozv2boql5xnww.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/hgwosudozv2boql5xnww.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 29,
        rname: "Egg Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/wn1mbestfmnwv6czczih.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/wn1mbestfmnwv6czczih.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/wn1mbestfmnwv6czczih.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 30,
        rname: "Egg Chilli Garlic Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/nmhydq49xqtalmyq21km.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/nmhydq49xqtalmyq21km.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/nmhydq49xqtalmyq21km.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 31,
        rname: "Chicken Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/auc4h3ddeus8yjqcv6zj.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/auc4h3ddeus8yjqcv6zj.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹250",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/auc4h3ddeus8yjqcv6zj.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 32,
        rname: "Chicken Chilli Garlic Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/zgmb8esyednqcuadlahr.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/zgmb8esyednqcuadlahr.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/zgmb8esyednqcuadlahr.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 33,
        rname: "Chicken Singapuri Noodles",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/zgmb8esyednqcuadlahr.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/zgmb8esyednqcuadlahr.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/zgmb8esyednqcuadlahr.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 34,
        rname: "Veg Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/wn1mbestfmnwv6czczih.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/wn1mbestfmnwv6czczih.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/wn1mbestfmnwv6czczih.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 35,
        rname: "Veg Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/ttpgt3wrb0wpumdk9cat.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/ttpgt3wrb0wpumdk9cat.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹225",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480190/ttpgt3wrb0wpumdk9cat.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 36,
        rname: "Veg Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/fejoaokmkdqq5gyl6wve.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/fejoaokmkdqq5gyl6wve.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹235",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480191/fejoaokmkdqq5gyl6wve.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 37,
        rname: "Egg Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/aj8no3b1acocxgvzo9v9.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/aj8no3b1acocxgvzo9v9.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/aj8no3b1acocxgvzo9v9.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 38,
        rname: "Egg Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/fxx6jwshvldwxvyc1hcg.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/fxx6jwshvldwxvyc1hcg.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹250",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480186/fxx6jwshvldwxvyc1hcg.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 39,
        rname: "Egg Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/g2prov7mqe9s8zjdxbl8.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/g2prov7mqe9s8zjdxbl8.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/g2prov7mqe9s8zjdxbl8.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 40,
        rname: "Chicken Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/d5ucast8dftjbcqomt14.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/d5ucast8dftjbcqomt14.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹250",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480183/d5ucast8dftjbcqomt14.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 41,
        rname: "Chicken Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/ughvopik9iyj3mkmwkcw.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/ughvopik9iyj3mkmwkcw.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480182/ughvopik9iyj3mkmwkcw.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 42,
        rname: "Chicken Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/dbptghqzbjnldqkmlze5.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/dbptghqzbjnldqkmlze5.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480184/dbptghqzbjnldqkmlze5.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 43,
        rname: "Prawn Fried Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/vl9zklm4xwcs3lkwrbbw.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/vl9zklm4xwcs3lkwrbbw.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹330",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/vl9zklm4xwcs3lkwrbbw.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 44,
        rname: "Prawn Chilli Garlic Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/ypavj5x5xlnv8xiexpov.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/ypavj5x5xlnv8xiexpov.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/ypavj5x5xlnv8xiexpov.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 45,
        rname: "Prawn Singapuri Rice",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/zd6bisyifhfrpxadz7n3.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/zd6bisyifhfrpxadz7n3.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/zd6bisyifhfrpxadz7n3.jpg",
        category:"Noodles and Rice Veg"
    },
    {
        id: 46,
        rname: "Veg Steamed Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/fn1xxvon7engvdrdhc9c.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/fn1xxvon7engvdrdhc9c.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹170",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480189/fn1xxvon7engvdrdhc9c.jpg",
        category:"Momos"
    },
    {
        id: 47,
        rname: "Veg Fried Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/gacjutwjsk1dxlzhzpye.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/gacjutwjsk1dxlzhzpye.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹180",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480187/gacjutwjsk1dxlzhzpye.jpg",
        category:"Momos"
    },
    {
        id: 48,
        rname: "Veg Kurkure Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹200",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        category:"Momos"
    },
    {
        id: 49,
        rname: "Paneer Steamed Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/pkumtvbgcpxzmoc8459a.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/pkumtvbgcpxzmoc8459a.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹175",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/pkumtvbgcpxzmoc8459a.jpg",
        category:"Momos"
    },
    {
        id: 50,
        rname: "Paneer Fried Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/ttmxtyvpqyn1az3yns5b.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/ttmxtyvpqyn1az3yns5b.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹200",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/ttmxtyvpqyn1az3yns5b.jpg",
        category:"Momos"
    },
    {
        id: 51,
        rname: "Paneer Kurkure Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹215",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/cdohbnidrhz5vnfgtec1.jpg",
        category:"Momos"
    },
    {
        id: 52,
        rname: "Chicken Steamed Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/sgbuukmb2qhg1jckshtk.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/sgbuukmb2qhg1jckshtk.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹220",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/sgbuukmb2qhg1jckshtk.jpg",
        category:"Momos"
    },
    {
        id: 53,
        rname: "Chicken Fried Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/ghlk2cfzq4kvciba4wt1.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/ghlk2cfzq4kvciba4wt1.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹220",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/ghlk2cfzq4kvciba4wt1.jpg",
        category:"Momos"
    },
    {
        id: 54,
        rname: "Chicken Kurkure Momos",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/rxzxyzowh0gjsbavodb8.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/rxzxyzowh0gjsbavodb8.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹270",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/rxzxyzowh0gjsbavodb8.jpg",
        category:"Momos"
    },
    {
        id: 55,
        rname: "Veg Chopsuey",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/p4lix5iwqfjbed7dng46.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/p4lix5iwqfjbed7dng46.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹210",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/p4lix5iwqfjbed7dng46.jpg",
        category:"Chopsuey"
    },
    {
        id: 56,
        rname: "Egg Chopsuey",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/hfysslckzazth2rvygqz.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/hfysslckzazth2rvygqz.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹220",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/hfysslckzazth2rvygqz.jpg",
        category:"Chopsuey"
    },
    {
        id: 57,
        rname: "Chicken Chopsuey",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/xppqt4fursxtvzog893i.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/xppqt4fursxtvzog893i.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹245",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/xppqt4fursxtvzog893i.jpg",
        category:"Chopsuey"
    },
    {
        id: 58,
        rname: "American Chopsuey",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/kxnchteoipg7afzauqws.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/kxnchteoipg7afzauqws.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹265",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/kxnchteoipg7afzauqws.jpg",
        category:"Chopsuey"
    },
    {
        id: 59,
        rname: "Veg Manchurian",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375666/gcsuztzojcdyxh1hhe23.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375666/gcsuztzojcdyxh1hhe23.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹325",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375666/gcsuztzojcdyxh1hhe23.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 60,
        rname: "Veg Sweet and Sour",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 61,
        rname: "Mixed Veg Hot Garlic",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 62,
        rname: "Mushroom Chilli Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/gqmvrvhkcb3q4qo9nnwi.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/gqmvrvhkcb3q4qo9nnwi.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719480185/gqmvrvhkcb3q4qo9nnwi.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 63,
        rname: "Veg Baby Corn Garlic Sauce",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 64,
        rname: "Paneer Hot Garlic Sauce",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/habjfpwxokayyvnpfhh3.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/habjfpwxokayyvnpfhh3.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375662/habjfpwxokayyvnpfhh3.jpg",
        category:"MainCourse(Veg)"
    },
    {
        id: 65,
        rname: "Chicken Manchurian Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/otnbbups4fxwd8bfw1b8.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/otnbbups4fxwd8bfw1b8.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹340",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/otnbbups4fxwd8bfw1b8.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 66,
        rname: "Chicken Chilly Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375663/kqqjyhtc22xf5gklndxu.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 67,
        rname: "Chicken Hot Garlic",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/r6vazsbr1g50wdldragz.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/r6vazsbr1g50wdldragz.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹350",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375664/r6vazsbr1g50wdldragz.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 68,
        rname: "Honey Chilli Chicken Gravy",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/kgppbdlahlghi73m8eyv.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/kgppbdlahlghi73m8eyv.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/kgppbdlahlghi73m8eyv.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 69,
        rname: "Chicken Sweet & sour",
        imgdata: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1719375665/yaomtiudr2hia58gfu2s.jpg",
        category:"MainCourse(NonVeg)"
    },
    {
        id: 70,
        rname: "Fried Rice /Noodles+Veg Manchurian",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 71,
        rname: "Chilli Potato+Noodles",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹240",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 72,
        rname: "Chilly Paneer+Noodle/Fried Rice",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹260",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 73,
        rname: "Fried Rice /Noodles+Chilli Chicken",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },

    {
        id: 74,
        rname: "Fried Rice /Noodles+Chicken Manchurian",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹300",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Combo(Veg)"
    },
    {
        id: 75,
        rname: "Half Chilly Paneer+Half veg Hakka Noodle+2 Spring roll+2 Veg momo",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹370",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"Veg Thali Combo"
    },
    {
        id: 75,
        rname: "Half Chilly Chicken+Half Chicken Hakka Noodle+2 Chicken Spring roll+2 Chicken momo",
        imgdata: "",
        address: "Burger, Sandwich, Fast Food",
        delimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        somedata: "2525 + order placed from here recently",
        price: "₹440",
        rating: "3.8",
        arrimg: "https://res.cloudinary.com/di0egnojl/image/upload/v1718341191/r0uqvjzcbgmzs3g6zaao.jpg",
        category:"NonVeg Thali Combo"
    },



];

export default Fooddata;